import type { FunctionComponent, PropsWithChildren } from 'react';
import Head from 'next/head';
import * as Base from '@/components/base';
import * as Core from '@/components/core';

interface Props {
  title: string;
}

export const LayoutApp: FunctionComponent<PropsWithChildren<Props>> = ({
  children,
  title,
}) => {
  return (
    <div className="bg-slate-200 h-screen">
      <Head>
        <title>MyTienda | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Core.HeaderApp></Core.HeaderApp>
      <Base.Container>{children}</Base.Container>
    </div>
  );
};
