import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import * as Core from '@/components/core';
import * as Base from '@/components/base';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MyTienda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Core.HeaderLading></Core.HeaderLading>
      <Base.Container className="mt-10">
        <div className="items-center lg:flex">
          <div className="w-full lg:w-1/2">
            <div className="lg:max-w-lg">
              <h1 className="text-2xl font-semibold text-gray-800 uppercase dark:text-white lg:text-3xl">
                MyTienda
              </h1>
              <p className="mt-2 text-gray-600">
                MyTienda es una tienda online que te permite vender tus
                productos a través de internet.
              </p>
              <p className="mt-2 text-gray-600">
                Crea tu cuenta y comienza a vender en línea.
              </p>
            </div>
          </div>

          <div className="flex items-center justify-center w-full mt-6 lg:mt-0 lg:w-1/2">
            <Image
              className="w-full h-full lg:max-w-2xl"
              src="https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg"
              width={720}
              height={600}
              alt="hero"
            ></Image>
          </div>
        </div>
      </Base.Container>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="text-center mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium text-center title-font text-gray-900 mb-4">
              Nuestros servicios
            </h1>
          </div>
          <div className="flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2">
            {['Venta', 'Compra', 'Cambio', 'Devolución'].map((item) => (
              <div key={item} className="p-2 sm:w-1/2 w-full">
                <div className="bg-gray-100 rounded flex p-4 h-full items-center">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="3"
                    className="text-indigo-500 w-6 h-6 flex-shrink-0 mr-4"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
                    <path d="M22 4L12 14.01l-3-3"></path>
                  </svg>
                  <span className="title-font font-medium">
                    {item}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      <Core.Footer></Core.Footer>
    </div>
  );
};

export default Home;
